[API]
is_production = false
base_url = http://127.0.0.1:8000
auth_endpoint = /core/api/Auth/authenticate
objects_endpoint = /core/api/objects/select
objects_metadata = /core/api/files/objects/{id}
download_endpoint = /core/api/files/objects/{id}/files/{blob_id}
username = your_username
password = your_password
polling_interval = 60

[Paths]
results_dir = ./results

[Processing]
save_images = true
dpi = 300
use_advanced_recognition = true

[Selection]
# Ключевые слова для поиска технических требований (через запятую)
keywords = материал,гост,допуски,требования,пункт,размеры,технические требования,общие допуски,покрытие,маркировать,сварка,пункт,пункты

[Exclusion]
# Ключевые слова для исключения блоков (подписи, штампы и т.п.)
exclude_keywords = подписан,сертификат,эцп,укэп,унэп,владелец подписи,действительно,действителен,квалифицированной,электронной подписью