version: "3.8"

services:
  ocr_app:
    build:
    # Контекст сборки – корень проекта (root)
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ocr_app_dwg_to_text
    user: "${UID}:${GID}"
    # (опционально) устанавливаем рабочую директорию внутри контейнера
    working_dir: /app
    environment:
      - MONITORED_DIR=${MONITORED_DIR}
      - UID=${UID}
      - GID=${GID}
    volumes:
      # Файл конфигурации, доступный только для чтения
      - type: bind
        source: ../config.ini
        target: /app/config.ini
        read_only: true
      # Каталог для мониторинга, с использованием переменной окружения
      - type: bind
        source: ../pdf
        target: ${MONITORED_DIR}
        consistency: consistent
    restart: unless-stopped
